project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://mtanviruzzaman.github.io/for-the-love-of-physics/
  repo-url: https://github.com/mtanviruzzaman/for-the-love-of-physics
  title: "For the love of Physics"
  navbar:
    right:
      - icon: github
        href: https://github.com/mtanviruzzaman/for-the-love-of-physics
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

comments:
  giscus:
    repo: mtanviruzzaman/for-the-love-of-physics
    category: Announcements
    mapping: pathname
    reactions-enabled: true

